eureka:
  client:
    service-url:
      # 在 C 盘下找到 host 文件，windows/system32/drivers/host
      defaultZone: http://server1:8761/eureka, http://server1:8762/eureka
spring:
  application:
    name: client
server:
  port: 8677